#!/bin/bash
dpkg-query -l >/tmp/dpkg.txt
grep -i dbus /tmp/dpkg.txt &> /dev/null
if [ $? -gt 0 ]; then
  apt-get install dbus
fi
grep -i vim /tmp/dpkg.txt &> /dev/null
if [ $? -gt 0 ]; then
  apt-get install vim
fi
rm /tmp/dpkg.txt

